{{- range $name, $agent := .Values.agents }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
spec:
  replicas: {{ $agent.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        fence-role: cognitive-agent
    spec:
      containers:
        - name: {{ $name }}
          image: {{ $agent.image }}
          command:
{{- if $agent.command }}
{{ toYaml $agent.command | indent 12 }}
{{- else }}
            - "/bin/sh"
            - "-c"
{{- end }}
          args:
{{- if $agent.args }}
          {{- range $arg := $agent.args }}
            - |
{{ tpl $arg $ | indent 14 }}
          {{- end }}
{{- else }}
            - |
              while true; do
                echo "Agent $(hostname) calling vLLM brain..."
                wget -qO- http://{{ $.Release.Name }}-vllm:80
                sleep 10;
              done
{{- end }}
{{- end }}
